#!/usr/bin/env python3
"""dtm2autoinput.py - turn a Dolphin input movie (.dtm) recorded on WiiStation
into an sd:/wiistation/autoinput.txt script.

For new recordings use scripts/movie_capture.sh instead: WiiStation records the pad
itself, in emulated vblanks. A .dtm counts host frames, which drift from the game's
vblanks whenever the emulation runs below full speed, so a converted movie goes out of
step. This stays for movies recorded before that existed.

Usage: dtm2autoinput.py MOVIE.dtm [--offset N] [--polls-per-frame F]
                        [--map A=Cross,B=Circle,...] [--out autoinput.txt] [--trace-after-start]

The DTM data area interleaves two record kinds in poll order with no frame
tags: GameCube pad polls (8 bytes: buttons0, buttons1, L, R, stickX, stickY,
cX, cY) and Wiimote reports (1 size byte + report, report id 0x30..0x3F).
The size byte + report id pair identifies Wiimote records reliably; every
other record is a pad poll. Time is estimated from the pad-poll index: the
header gives total polls and total VI frames, so polls per frame is known.

The GameCube buttons are mapped to PSX buttons with WiiStation's default
GameCube mapping (override with --map). Output lines are
"<vblank> <hex PSX mask>" plus, with --trace-after-start, a "trace" line
60 vblanks after every Start press (for the debug build's primitive trace).
--offset shifts every vblank (the movie starts when recording started, the
autoboot timeline starts at power-on; find the offset once from the first
Start press and reuse it).
"""
import argparse, struct, sys

PSX = {"Select": 0x0001, "L3": 0x0002, "R3": 0x0004, "Start": 0x0008, "Up": 0x0010, "Right": 0x0020,
       "Down": 0x0040, "Left": 0x0080, "L2": 0x0100, "R2": 0x0200, "L1": 0x0400, "R1": 0x0800,
       "Triangle": 0x1000, "Circle": 0x2000, "Cross": 0x4000, "Square": 0x8000}
GC0 = ["Start", "A", "B", "X", "Y", "Z", "Up", "Down"]          # byte 0 bits
GC1 = ["Left", "Right", "L", "R"]                                # byte 1 bits 0..3
# WiiStation's default GameCube mapping (Gamecube/gc_input/controller-GC.c):
# A Cross, B Square, X Circle, Y Triangle, Start (without Z) Start, Start+Z Select, L L1, R R1.
DEFAULT_MAP = {"A": "Cross", "B": "Square", "X": "Circle", "Y": "Triangle", "Start": "Start",
               "L": "L1", "R": "R1", "Up": "Up", "Down": "Down", "Left": "Left", "Right": "Right"}

def parse(path):
    """Split the data area. A pad poll is 8 bytes whose second byte carries the
    is_connected bit (0x40); a Wiimote record is a size byte followed by a
    serialized state whose first byte is a flags byte with that bit clear."""
    b = open(path, "rb").read()
    hdr = {"from_savestate": b[0x0C], "controllers": b[0x0B],
           "vi": struct.unpack_from("<Q", b, 0x0D)[0], "inputs": struct.unpack_from("<Q", b, 0x15)[0]}
    data = b[256:]
    polls = []          # (poll_index, buttons0, buttons1)
    pos, wm = 0, 0
    while pos + 2 <= len(data):
        if data[pos + 1] & 0x40:
            polls.append((len(polls), data[pos], data[pos + 1] & 0x0F)); pos += 8
        else:
            pos += 1 + data[pos]; wm += 1
    hdr["polls_parsed"] = len(polls); hdr["wiimote_records"] = wm
    return hdr, polls

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("movie"); ap.add_argument("--offset", type=int, default=0)
    ap.add_argument("--polls-per-frame", type=float, default=0.0)
    ap.add_argument("--map", default=""); ap.add_argument("--out", default="")
    ap.add_argument("--trace-after-start", action="store_true")
    a = ap.parse_args()
    hdr, polls = parse(a.movie)
    # time base: parsed pad polls per VI frame (the header's input count also counts Wiimote records)
    ppf = a.polls_per_frame or (hdr["polls_parsed"] / hdr["vi"] if hdr["vi"] else 1.0)
    gcmap = dict(DEFAULT_MAP)
    for kv in filter(None, a.map.split(",")):
        k, v = kv.split("="); gcmap[k] = v
    print(f"# {a.movie}: from_savestate={hdr['from_savestate']} VI={hdr['vi']} pad polls={hdr['inputs']} "
          f"(parsed {hdr['polls_parsed']}, wiimote records {hdr['wiimote_records']}), {ppf:.2f} polls/frame", file=sys.stderr)
    events, last = [], None
    for idx, b0, b1 in polls:
        names = [n for i, n in enumerate(GC0) if b0 & (1 << i)] + [n for i, n in enumerate(GC1) if b1 & (1 << i)]
        mask = 0
        for n in names:
            p = gcmap.get(n)
            if p in PSX: mask |= PSX[p]
        if mask != last:
            events.append((int(idx / ppf), mask, names)); last = mask
    lines = [f"# generated by scripts/dtm2autoinput.py from {a.movie} (offset {a.offset})"]
    for frame, mask, names in events:
        vbl = frame + a.offset
        lines.append(f"{vbl} {mask:04x}" + (f"   # {' '.join(names)}" if names else ""))
        if a.trace_after_start and mask & PSX["Start"]:
            lines.append(f"trace {vbl + 60}")
    text = "\n".join(lines) + "\n"
    if a.out:
        open(a.out, "w", newline="\n").write(text); print(f"# wrote {a.out}: {len(events)} events", file=sys.stderr)
    else:
        sys.stdout.write(text)

if __name__ == "__main__":
    main()
